# Generated by Django 4.1.1 on 2022-10-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonproject', '0004_addition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addition',
            old_name='title',
            new_name='name',
        ),
    ]
