# Generated by Django 4.1.1 on 2022-10-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonproject', '0005_rename_title_addition_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addition',
            old_name='description',
            new_name='detai',
        ),
    ]
